---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: table-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: table-manager
    spec:
      containers:
      - name: table-manager
        image: quay.io/cortexproject/cortex:v0.4.0
        imagePullPolicy: IfNotPresent
        args:
        - -target=table-manager
        - -server.http-listen-port=80
        - -cassandra.addresses=cassie-cassandra.default.svc.cluster.local
        - -cassandra.keyspace=cortex_new
        - -cassandra.timeout=1000ms
        - -cassandra.replication-factor=2
        - -chunk.storage-client=cassandra
        - -dynamodb.chunk-table.period=168h0m0s
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2017-01-06
        - -dynamodb.daily-buckets-from=2017-01-10
        - -dynamodb.base64-buckets-from=2017-01-17
        - -dynamodb.v4-schema-from=2017-02-05
        - -dynamodb.v5-schema-from=2017-02-22
        - -dynamodb.v6-schema-from=2017-03-19
        - -dynamodb.chunk-table.from=2017-04-17
        ports:
        - containerPort: 80
